sonar.organization=jamessawle
sonar.projectKey=jamessawle_sbxflow

sonar.sources=.
sonar.exclusions=dist/**,**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
